# Generated by Django 3.2.18 on 2023-04-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('status_email', models.CharField(choices=[('A', 'Ativo'), ('N', 'Não confirmado'), ('I', 'Inválido'), ('S', 'Spam'), ('O', 'Opt-out')], default='N', max_length=1, verbose_name='Status Email')),
            ],
        ),
    ]
