# Generated by Django 3.2.22 on 2023-10-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_recurso_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plain_header',
            field=models.BooleanField(default=False),
        ),
    ]
