# Generated by Django 3.2.18 on 2023-04-01 15:15

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('token', models.CharField(default=utils.models.create_token, max_length=30, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
