# Generated by Django 3.2.18 on 2023-04-01 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagestore.utils
import sorl.thumbnail.fields
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('brief', models.CharField(blank=True, default='', help_text='Short description', max_length=255, verbose_name='Brief')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is public')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ('order', 'created', 'name'),
                'permissions': (('moderate_albums', 'View, update and delete any album'),),
                'abstract': False,
                'swappable': 'IMAGESTORE_ALBUM_MODEL',
            },
        ),
        migrations.CreateModel(
            name='AlbumUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(help_text='Select a .zip file of images to upload into a new Gallery.', upload_to='temp/', verbose_name='images file (.zip)')),
                ('new_album_name', models.CharField(blank=True, help_text='If not empty new album with this name will be created and images will be upload to this album', max_length=255, verbose_name='New album name')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='tags')),
                ('album', models.ForeignKey(blank=True, help_text='Select an album to add these images to. leave this empty to create a new album from the supplied title.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.IMAGESTORE_ALBUM_MODEL)),
            ],
            options={
                'verbose_name': 'Album upload',
                'verbose_name_plural': 'Album uploads',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('tags', tagging.fields.TagField(blank=True, max_length=255, verbose_name='Tags')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('image', sorl.thumbnail.fields.ImageField(max_length=255, upload_to=imagestore.utils.FilePathGenerator(to='uploads/gallery/'), verbose_name='File')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.IMAGESTORE_ALBUM_MODEL, verbose_name='Album')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('order', 'id'),
                'permissions': (('moderate_images', 'View, update and delete any image'),),
                'abstract': False,
                'swappable': 'IMAGESTORE_IMAGE_MODEL',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of', to=settings.IMAGESTORE_IMAGE_MODEL, verbose_name='Head'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
